propal_fdj:
    resource: "@PropalFDJBundle/Resources/config/routing.yml"
    prefix:   /fdj/

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc.html
